### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by buzzdead** [buzzdead/Hypertrophy#15]
Expand the possibilities of progress tracking:

- [x] Make it possible to see a sub sidebar or something for exercise types within the categories, i.e front lateral exercises on the graph specifically.
- [x] Make it possible to see metric progress. #30 
- [ ] Daily\weekly\monthly toggle

 Future release: Make it possible to show multiple graphs, so one can compare historically etc...!
